import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header01 from "@/components/blocks/header-01";

import ErrorTestButton from "./error-test-button";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header01 />

          {/* Botão de teste para erros - apenas em desenvolvimento */}
          {process.env.NODE_ENV === "development" && (
            <div className="bg-red-50 border-b border-red-200 p-2">
              <div className="container mx-auto px-4 flex justify-center">
                <ErrorTestButton />
              </div>
            </div>
          )}

          <div className="container mx-auto px-4 py-12">
            <ErrorWrapper>{children}</ErrorWrapper>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
